// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQKSHv7jgfN-oHHv7ryQMYYC5ZhTeaPEQ',
    appId: '1:711051185991:web:d4a6043bf50f30f55c4662',
    messagingSenderId: '711051185991',
    projectId: 'eduspace-6dcb1',
    authDomain: 'eduspace-6dcb1.firebaseapp.com',
    storageBucket: 'eduspace-6dcb1.firebasestorage.app',
    measurementId: 'G-Q7JVCWP0SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9BMfOIEi3oKBbDDCPV-7vahBiUKTUikw',
    appId: '1:711051185991:android:201e39c4e1ec94ba5c4662',
    messagingSenderId: '711051185991',
    projectId: 'eduspace-6dcb1',
    storageBucket: 'eduspace-6dcb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwF2ljmPZYcR3wI1CFuw_Zo5xusXiByqk',
    appId: '1:711051185991:ios:65725142a60414a55c4662',
    messagingSenderId: '711051185991',
    projectId: 'eduspace-6dcb1',
    storageBucket: 'eduspace-6dcb1.firebasestorage.app',
    iosBundleId: 'com.example.eduspaceFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwF2ljmPZYcR3wI1CFuw_Zo5xusXiByqk',
    appId: '1:711051185991:ios:65725142a60414a55c4662',
    messagingSenderId: '711051185991',
    projectId: 'eduspace-6dcb1',
    storageBucket: 'eduspace-6dcb1.firebasestorage.app',
    iosBundleId: 'com.example.eduspaceFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQKSHv7jgfN-oHHv7ryQMYYC5ZhTeaPEQ',
    appId: '1:711051185991:web:5460403f557ffae55c4662',
    messagingSenderId: '711051185991',
    projectId: 'eduspace-6dcb1',
    authDomain: 'eduspace-6dcb1.firebaseapp.com',
    storageBucket: 'eduspace-6dcb1.firebasestorage.app',
    measurementId: 'G-HSV4KZ9YX2',
  );
}
